### ISSUE TITLE
Feature Request: Add shortcut to set case explicitly instead of toggling

### ISSUE THREAD

**Issue by shayded-exe** [MatthewAlner/obsidian-toggle-case#1]
My primary use of this extension is converting things to title case.

It would be nice to have separate shortcuts for each case.

**Comment by MatthewAlner** [comment]
Hey @shayded-exe, thanks for your request. I've considered it and i'm sorry but I think that i'd rather keep this plugin hyper focused, so all the "Toggle Case" plugin does it toggle cases.

[obsidian-editor-shortcuts](https://github.com/timhor/obsidian-editor-shortcuts) does exactly what you are asking for however, so I hope that is a satisfactory answer 😄

There is also [obsidian-text-format](https://github.com/Benature/obsidian-text-format) which is even more comprehensive, but i'm not sure if it will let you bind keys
